// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mksucmbgejucmbuvrrij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1rc3VjbWJnZWp1Y21idXZycmlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE0Nzc4OTksImV4cCI6MjA3NzA1Mzg5OX0.AavrydR0d7zozdz9HhXzMcRSeJUUju52yYnK3wTAIYk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});